---
- hosts: all
  become: yes  
  tasks:
  - name: stop firewall 
    service:
      name: firewalld
      state: stopped
      enabled: no
  - name: SELinux disable
    replace:
      dest: /etc/selinux/config
      regexp: 'SELINUX=enforcing'
      replace: 'SELINUX=disabled'
  - name: stop dhclinet
    yum:
      name: dhcpd
      state: absent
  - name: stop NetworkManager
    service:
      name: NetworkManager
#      state: stopped
      enabled: no
  - reboot:
  - name: start network
    service:
      name: network
      state: started
      enabled: yes
  - name: update packages
    yum: 
      name: '*' 
      state: latest
  - name: install open train
    yum:
      name: centos-release-openstack-train
      state: installed
  - reboot:
